# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
    inputs:
      promote:
        description: 'Force promote docker image to registry'
        required: false
        default: 'false'
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main


jobs:

  promote-docker-image:
    runs-on: ubuntu-latest



    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event.inputs.promote == 'true' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Next Version
        id: get_next_version
        run: |
          echo "next_version=1.0.0" >> $GITHUB_OUTPUT

      - name: Create Docker Tag
        id: create_docker_tag
        shell: bash
        run: |
          CLEANED_BRANCH_NAME=$(echo "${GITHUB_REF_NAME}" | sed 's/[^a-zA-Z0-9._-]/-/g')
          TAG_SUFFIX=""
          if [ "${GITHUB_REF_NAME}" != "main" ]; then
            TAG_SUFFIX="${CLEANED_BRANCH_NAME}-"
          fi
          echo "docker_tag=${TAG_SUFFIX}${{ steps.get_next_version.outputs.next_version }}" >> $GITHUB_OUTPUT

      - name: Promote to Docker Image Registry
        run: |
          echo "Promoting Docker image to registry..."
          echo "Docker tag: ${{ steps.create_docker_tag.outputs.docker_tag }}"


      - name: Get Tag and SHA
        id: get_git_tag_sha
        shell: bash
        run: |
          echo "tag_name=build-${{ github.head_ref || github.ref_name }}-$(date +'%Y%m%d%H%M%S')-v${{ steps.get_next_version.outputs.next_version }}" >> $GITHUB_OUTPUT
          echo "sha_ref=${{ github.sha || github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT

      - name: Create Build Tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.get_git_tag_sha.outputs.tag_name }}',
              sha: '${{ steps.get_git_tag_sha.outputs.sha_ref }}'
            });
