name: Pull Request Validation
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  ci-test:
    uses: ./.github/workflows/ci-test.yaml
    secrets: inherit
