name: notify-dogs.yaml
on:
  workflow_call:
    inputs:
      catName:
        type: string
        required: true
        description: Name of the cat

jobs:
  notify-dogs:
    runs-on: ubuntu-latest
    steps:
      - name: notify-dogs
        run: echo "The cat's name is ${{ inputs.catName }}. Woof!"
