name: notify-dogs.yaml
on:
  workflow_call:
    inputs:
      generationOutcome:
        type: string
        required: true
        description: Outcome of the cat name generation job (e.g., success, failure)
      catName:
        type: string
        required: false
        description: Name of the cat
      channel:
        type: string
        required: true
        description: Channel to send the notification to

jobs:
  notify-dogs:
    runs-on: self-hosted
    steps:
      - name: notify-dogs
        shell: bash
        run: |
            if [ "${{ inputs.generationOutcome }}" == "success" ]; then
                echo "Cat name:  ${{ inputs.catName }} sent to channel: ${{ inputs.channel }}"
            else
                echo "Cat name generation failed."
            fi

