name: Pull Request Validation
env:
  SERVICE_NAME: ter
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ci-test:
    uses: ./.github/workflows/ci-test.yaml
    secrets: inherit
