name: run-all-cats

on: [ workflow_call ]

jobs:
  cat-dev:
    uses: './.github/workflows/run-cat-dev.yaml'
    secrets: inherit
  cat-prod:
    strategy:
      matrix:
        catType: [lion, tiger, panther, lynx]
    uses: './.github/workflows/run-cat-prod.yaml'
    with:
      catType: ${{ matrix.catType }}
    secrets: inherit
