name: run-cat-prod

on:
  workflow_call:
    inputs:
      catType:
        type: string
      path:
        type: string

jobs:
  run-cats:
    name: run-cats-${{ inputs.catType }}
    runs-on: self-hosted
    environment: prod

    outputs:
      catName: ${{ steps.run-cats.outputs.catName }}
      outcome: ${{ steps.run-cats.outcome }}
      channel: ${{ vars.CHANNEL_NAME }}

    steps:
      - uses: actions/checkout@v4
      - name: run-cats
        id: run-cats
        uses: ./.github/actions/cat-name-generator
        with:
          catType: ${{ inputs.catType }}
          path: ${{ inputs.path }}

  notify-dogs:
    needs: [ run-cats ]
    name: notify-dogs-${{ inputs.catType }}
    if: always()
    uses: ./.github/workflows/notify-dogs.yaml
    with:
      catName: ${{ needs.run-cats.outputs.catName }}
      generationOutcome: ${{ needs.run-cats.outputs.outcome }}
      channel: ${{ needs.run-cats.outputs.channel }}
