name: run-cat-1

on: [ workflow_call ]

jobs:
  run-cats:
    runs-on: self-hosted
    strategy:
      matrix:
        catType: [lion, tiger, panther, lynx]
    outputs:
      catName: ${{ steps.run-cats.outputs.catName }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: run-cats
        id: run-cats
        uses: ./.github/actions/run-cats
        with:
          catType: ${{ matrix.catType }}

  notify-dogs:
    needs: [ run-cats ]
    if: always()
    uses: "./.github/workflows/notify-dogs.yaml"
    with:
      catName: ${{ needs.run-cats.outputs.catName }}
