name: run-cat-prod

on:
  workflow_call:
    inputs:
      catType:
        type: string

jobs:

  run-cats:
    name: run-cats-${{ inputs.catType }}
    runs-on: self-hosted

    outputs:
      catName: ${{ steps.run-cats.outputs.catName }}
      outcome: ${{ steps.run-cats.outcome }}

    steps:
      - uses: actions/checkout@v4
      - name: run-cats
        id: run-cats
        uses: ./.github/actions/cat-name-generator
        with:
          catType: ${{ inputs.catType }}


  notify-dogs:
    needs: [ run-cats ]
    environment: prod
    name: notify-dogs-${{ inputs.catType }}
    runs-on: self-hosted
    steps:
      - name: notify-dogs
        if: always()
        uses: ./.github/workflows/notify-dogs.yaml
        with:
          catName: ${{ needs.run-cats.outputs.catName }}
          generationOutcome: ${{ needs.run-cats.outputs.outcome }}
          channel: ${{ vars.CHANNEL_NAME }}
