name: run-deployment-dev

on: [ workflow_call ]

jobs:

  run-deployments:
    runs-on: self-hosted
    environment: dev
    strategy:
      matrix:
        country: [ us, ca, uk ]
        deploymentType: [ v1,v2 ]
    outputs:
      deploymentOutput: ${{ steps.run-dev-deployments.outputs.deploymentOutput }}
      outcome: ${{ steps.run-dev-deployments.outcome }}
      channel: ${{ vars.CHANNEL_NAME }}
    steps:
      - uses: actions/checkout@v4

      - name: Print job ID
        run: |
          echo "Job ID: ${{ github.job }}"

      - name: run-dev-deployments
        id: run-dev-deployments
        uses: ./.github/actions/name-generator
        with:
          deploymentType: ${{ matrix.deploymentType }}
          country: ${{ matrix.country }}


  notify:
    needs: [ run-deployments ]
    if: always()
    uses: "./.github/workflows/slack-notify.yaml"
    with:
      deploymentOutput: ${{ needs.run-deployments.outputs.deploymentOutput }}
      generationOutcome: ${{ needs.run-deployments.outputs.outcome }}
      channel: ${{ needs.run-deployments.outputs.channel }}
