name: run-cat-2

on:
  workflow_call:
    inputs:
      catType:
        type: string

jobs:
  run-cats:
    runs-on: self-hosted

    outputs:
      catName: ${{ steps.run-cats.outputs.catName }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: run-cats
        id: run-cats
        uses: ./.github/actions/run-cats
        with:
          catType: ${{ inputs.catType }}


  notify-dogs:
    needs: [ run-cats ]
    if: always()
    uses: "./.github/workflows/notify-dogs.yaml"
    with:
      catName: ${{ needs.run-cats.outputs.catName }}
