name: auto-generate-job
on:
  push:
    branches:
      - main
#    paths:
#      - 'dev/team1/**'
  #just for testing
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install yq
        run: sudo apt-get update && sudo snap install yq

      - name: run creates.sh script
        run: ./dev/team1/create.sh

      - name: Commit and Push Changes
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add .
          git commit -m "Automated commit by GitHub Actions"
          git push origin master
